<?php
	/**current_posts
		blockgenerator
		* Implements hook_help().
		*
		* Displays help and module information.
		*
		* @param path 
		*   Which path of the site we're using to display help
		* @param arg 
		*   Array that holds the current path as returned from arg() function
	*/
	function blockgenerator_help($path, $arg) {
		switch ($path) {
			case "admin/help#blockgenerator":
			return '' . t("Go to block Configuration page. Add or update Block then you will see new Country Option inside Visibility Setting.") . '';
			break;
		}
	}

	/**
		* Implements hook_block_list_alter().
	*/
	function blockgenerator_block_list_alter(&$blocks) {
		$result = db_query('SELECT delta, allowed_countries, notallowed_countries FROM block_generator');
		$countries = array();
		foreach ($result as $record) {
			$country = array(
				'allowed' => $record->allowed_countries,
				'notallowed' => $record->notallowed_countries
			);
			$countries[$record->delta] = $country;
		}
		foreach ($blocks as $key => $block) {
			$country_code = $_SESSION['smart_ip']['location']['country_code'];
			if (isset($countries[$block->delta]))
			{
				$country_list = $countries[$block->delta];

				if (strlen($country_list['allowed']) > 0)
				{
					if ((strpos($country_list['allowed'], $country_code) === FALSE)) {
						unset($blocks[$key]);
					}
				}
				else
				{
					if ((strpos($country_list['notallowed'], $country_code) !== FALSE)) {
						unset($blocks[$key]);
					}
				}
			}
    	}
	}
					
	/**
	 * Implements hook_form_FORM_ID_alter() to alter block_admin_configure from block module.
	 */	
	function blockgenerator_form_block_admin_configure_alter(&$form, &$form_state, $form_id) {
		//$form = block_admin_configure($form, $form_state, $module, $delta); 
		$delta = $form['delta']['#value'];
		
		$block_country = db_select('block_generator','b')
		->fields('b')
		->condition('delta', $delta)
		->execute()->fetch();
		
		$form['visibility']['country']= array(
		'#type' => 'fieldset',
		'#title' => t('Country'),
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
		'#group' => 'visibility',
		'#weight' => 20,
		);
		
		$form['visibility']['country']['allowed_countries'] = array(
		'#type' => 'textfield',
		'#title' => t('Allowed Country'),    
		'#description' => t('Limit to the listed Countries that are able to view the block. If empty, all countries except the not allowed can view the block. Write the country code and separate each country by space. Ex : US CA AU'),
		'#default_value' => isset($block_country->allowed_countries)?$block_country->allowed_countries:'',
		);
		
		$form['visibility']['country']['notallowed_countries'] = array(
		'#type' => 'textfield',
		'#title' => t('Not Allowed Country'),    
		'#description' => t('Hide the block to the listed Countries. Write the country code and separate each country by space. Ex : US CA AU'),
		'#default_value' => isset($block_country->notallowed_countries)?$block_country->notallowed_countries:'',
		);		
		
		// attach function to submit handler
		$form['#submit'][] = 'blockgenerator_form_block_admin_configure_submit_alter';
		//return $form;
	}	
	
	/**
	 * Implements hook_form_FORM_ID_alter() to alter block_add_block_form function from block module.
	 */
	function blockgenerator_form_block_add_block_form_alter(&$form, &$form_state, $form_id) {
		//$form = block_admin_configure($form, $form_state, $module, $delta); 
		
		$form['visibility']['country']= array(
			'#type' => 'fieldset',
			'#title' => t('Country'),
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#group' => 'visibility',
			'#weight' => 20,
		);
		
		$form['visibility']['country']['allowed_countries'] = array(
		'#type' => 'textfield',
		'#title' => t('Allowed Country'),    
		'#description' => t('Limit to the listed Countries that are able to view the block. If empty, all countries except the not allowed can view the block. Write the country code and separate each country by space. Ex : US CA AU'),
		'#default_value' => '',
		);
		
		$form['visibility']['country']['notallowed_countries'] = array(
		'#type' => 'textfield',
		'#title' => t('Not Allowed Country'),    
		'#description' => t('Hide the block to the listed Countries. Write the country code and separate each country by space. Ex : US CA AU'),
		'#default_value' => '',
		);
		
		// attach function to submit handler
		$form['#submit'][] = 'blockgenerator_form_block_add_block_form_submit_alter';
		//return $form;
	}
	
	// submit handler on block update
	function blockgenerator_form_block_admin_configure_submit_alter(&$form, &$form_state) {
	
		// check if config is already exist
		$query = db_select('block_generator','b')
		->fields('b')
		->condition('delta', $form_state['values']['delta'])
		->execute()->fetchAssoc();
		
		// if related data exist then update otherwise insert new data
		if (is_array($query)){
			db_update('block_generator')
			->fields(array(
			'allowed_countries' => $form_state['values']['allowed_countries'],
			'notallowed_countries' => $form_state['values']['notallowed_countries'],
			))
			->condition('delta', $form_state['values']['delta'])
			->execute();
		}
		else{
			db_insert('block_generator')
			->fields(array(
			'allowed_countries' => $form_state['values']['allowed_countries'],
			'notallowed_countries' => $form_state['values']['notallowed_countries'],
			'delta' => $form_state['values']['delta'],
			))				
			->execute();
		}
		
	}
	
	// submit handler on block insert
	function blockgenerator_form_block_add_block_form_submit_alter(&$form, &$form_state) {	
	
		// check if config is already exist
		$query = db_select('block_generator','b')
		->fields('b')
		->condition('delta', $form_state['values']['delta'])
		->execute()->fetchAssoc();
		
		// if related data exist then update otherwise insert new data
		if (is_array($query)){
			db_update('block_generator')
			->fields(array(
			'allowed_countries' => $form_state['values']['allowed_countries'],
			'notallowed_countries' => $form_state['values']['notallowed_countries'],
			))
			->condition('delta', $form_state['values']['delta'])
			->execute();
		}
		else{
			db_insert('block_generator')
			->fields(array(
			'allowed_countries' => $form_state['values']['allowed_countries'],
			'notallowed_countries' => $form_state['values']['notallowed_countries'],
			'delta' => $form_state['values']['delta'],
			))				
			->execute();
		}
	}	
	
	
	function blockgenerator_form_block_custom_block_delete_submit_alter(&$form, &$form_state) {		
		db_delete('block_generator')		
		->condition('delta', $form_state['values']['bid'])
		->execute();
	}	
